FROM docker.n8n.io/n8nio/n8n:2.4.5

ENV GENERIC_TIMEZONE=America/Sao_Paulo
ENV TZ=America/Sao_Paulo
ENV N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
ENV N8N_RUNNERS_ENABLED=true

ENV DB_TYPE=postgresdb
ENV DB_POSTGRESDB_PORT=5432
ENV DB_POSTGRESDB_SCHEMA=public

ENV N8N_PORT=5678
ENV N8N_HOST=0.0.0.0
ENV N8N_PROTOCOL=https

EXPOSE 5678
